### ISSUE TITLE
Bug when refreshing index

### ISSUE THREAD

**Issue by cdarken** [jay3/jayps_search#8]
Shouldn't the line https://github.com/jay3/jayps_search/blob/master/classes/orm/behaviour/searchable.php#L189
actually be:
```
'boost' => isset($prop['boost']) ? $prop['boost'] : ((strcmp($prop, $item->title_property()) === 0) && !empty($config['title_boost']) ? $config['title_boost'] : 0),
```
as the method `title_property()` does not belong to this class?

**Comment by jay3** [comment]
Thanks for reporting the issue and for the fix
